name: maven package deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Deploy
        env:
          GITHUB_PACKAGE_DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn --settings .mvn/project-settings.xml deploy